CREATE SCHEMA IF NOT EXISTS HOSPITALCENTER;

USE HOSPITALCENTER;

CREATE TABLE IF NOT EXISTS ADMINISTRADOR(
  CODIGO VARCHAR(45) NOT NULL,
  dpi VARCHAR(13) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  contraseña VARCHAR(45) NOT NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CODIGO VARCHAR(45) NOT NULL,
	nombre VARCHAR(45) NOT NULL,
	colegiado VARCHAR(45) NOT NULL,
	dpi VARCHAR(200) NOT NULL,
	telefono VARCHAR(8) NOT NULL,
	email VARCHAR(100) NOT NULL,
	horario_inicio TIME NOT NULL,
	horario_fin TIME NOT NULL,
	fecha_inicio_trabajo DATE NOT NULL,
	contraseña VARCHAR(45) NOT NULL,
	PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS TITULO(
  ID INT NOT NULL AUTO_INCREMENT,
  nombre_especialidad VARCHAR(200) NOT NULL,
  codigo_medico VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(codigo_medico) REFERENCES MEDICO(CODIGO)
);

CREATE TABLE IF NOT EXISTS LABORATORISTA(
  CODIGO VARCHAR(45) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  registro VARCHAR(45) NOT NULL,
  dpi VARCHAR(13) NOT NULL,
  telefono VARCHAR(8) NOT NULL,
  tipo_examen VARCHAR(100) NOT NULL,
  email VARCHAR(45) NOT NULL,
  fecha_inicio_trabajo DATE NOT NULL,
  contraseña VARCHAR(45) NOT NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS DIAS_TRABAJO(
  ID INT NOT NULL AUTO_INCREMENT,
  dia VARCHAR(45) NOT NULL,
  laboratorista VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(laboratorista) REFERENCES LABORATORISTA(CODIGO)
);

CREATE TABLE IF NOT EXISTS PACIENTE(
  CODIGO VARCHAR(45) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  sexo VARCHAR(45) NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  dpi VARCHAR(13) NOT NULL,
  telefono VARCHAR(8) NOT NULL,
  peso VARCHAR(45) NOT NULL,
  tipo_sangre VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  contraseña VARCHAR(45) NOT NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS EXAMEN(
  CODIGO VARCHAR(45) NOT NULL,
  nombre VARCHAR(450) NOT NULL,
  orden BOOLEAN NOT NULL,
  descripcion TEXT NOT NULL,
  costo DOUBLE NOT NULL,
  informe_tipo VARCHAR(45) NOT NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS REPORTE(
  CODIGO VARCHAR(45) NOT NULL,
  codigo_paciente VARCHAR(45) NOT NULL,
  codigo_medico VARCHAR(45) NOT NULL,
  informe TEXT,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  PRIMARY KEY(CODIGO),
  FOREIGN KEY(codigo_paciente) REFERENCES PACIENTE(CODIGO),
  FOREIGN KEY(codigo_medico) REFERENCES MEDICO(CODIGO)
);

CREATE TABLE IF NOT EXISTS CITA(
  CODIGO VARCHAR(45) NOT NULL,
  codigo_paciente VARCHAR(45) NOT NULL,
  codigo_medico VARCHAR(45) NOT NULL,
  especialidad VARCHAR(200) NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  PRIMARY KEY(CODIGO),
  FOREIGN KEY(codigo_paciente) REFERENCES PACIENTE(CODIGO),
  FOREIGN KEY(codigo_medico) REFERENCES MEDICO(CODIGO)
);

CREATE TABLE IF NOT EXISTS RESULTADO(
  CODIGO VARCHAR(45) NOT NULL,
  codigo_paciente VARCHAR(45) NOT NULL,
  codigo_medico VARCHAR(45) NOT NULL,
  codigo_examen VARCHAR(45) NOT NULL,
  codigo_laboratorista VARCHAR(45) NOT NULL,
  orden_path VARCHAR(100) NOT NULL,
  informe_path VARCHAR(100) NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  PRIMARY KEY(CODIGO),
  FOREIGN KEY(codigo_paciente) REFERENCES PACIENTE(CODIGO),
  FOREIGN KEY(codigo_medico) REFERENCES MEDICO(CODIGO),
  FOREIGN KEY(codigo_examen) REFERENCES EXAMEN(CODIGO),
  FOREIGN KEY(codigo_laboratorista) REFERENCES LABORATORISTA(CODIGO)
);

CREATE TABLE IF NOT EXISTS CONSULTA(
  ID INT NOT NULL AUTO_INCREMENT,
  TIPO_CONSULTA VARCHAR(200) NOT NULL,
  costo DOUBLE NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS HISTORIAL_MEDICO(
  ID INT NOT NULL AUTO_INCREMENT,
  codigo_resultado VARCHAR(45) NOT NULL,
  codigo_cita VARCHAR(45) NOT NULL,
  codigo_paciente VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(codigo_resultado) REFERENCES RESULTADO(CODIGO),
  FOREIGN KEY(codigo_cita) REFERENCES CITA(CODIGO),
  FOREIGN KEY(codigo_paciente) REFERENCES PACIENTE(CODIGO)
);

CREATE TABLE IF NOT EXISTS USUARIOS(
	ID INT NOT NULL AUTO_INCREMENT,
	contraseña VARCHAR(200) NOT NULL,
	tipo VARCHAR(45) NOT NULL,
    codigo VARCHAR(45) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS SOLICITUDES(
	ID INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(45) NOT NULL,
	sexo VARCHAR(45) NOT NULL,
	fecha_nacimiento DATE NOT NULL,
	dpi VARCHAR(13) NOT NULL,
	telefono VARCHAR(8) NOT NULL,
	peso VARCHAR(45) NOT NULL,
	tipo_sangre VARCHAR(45) NOT NULL,
	email VARCHAR(45) NOT NULL,
	contraseña VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID)
);
